[env:esp32-c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

build_flags = 
    -DMINER_VERSION='"v4.0-AutoDetect"'
    -DEEPROMSIZE=128
    -O3
    -DBOARD_ESP32_C6
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_MBEDTLS_HARDWARE_SHA=1
    ; ... thêm các flag khác nếu cần

lib_deps = 
    tzapu/WiFiManager
    bblanchon/ArduinoJson
    me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    paulstoffregen/Time
    arduino-libraries/NTPClient
    links2004/WebSockets@^2.5.0   ; <-- bản mới tương thích core 3.x
